-- Demo-controlled Aviator signal backend.
-- Use this only for the project's own simulator/demo mode. A public fair game
-- should not reveal future outcomes to players before the round resolves.

create table if not exists public.aviator_rounds (
  round_id bigint generated by default as identity primary key,
  target_x numeric(8,2) not null check (target_x >= 1.01 and target_x <= 99.99),
  signal_reveal_at timestamptz not null,
  betting_at timestamptz not null,
  fly_at timestamptz not null,
  crash_at timestamptz not null,
  status text not null check (status in ('scheduled', 'revealed', 'betting', 'flying', 'crashed')),
  server_seed_hash text not null,
  server_seed text,
  client_seed text not null default 'prime-vai-devx-demo',
  nonce bigint not null,
  source text not null default 'auto' check (source in ('auto', 'manual')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.aviator_signal_settings (
  id boolean primary key default true,
  auto_mode boolean not null default true,
  signal_active boolean not null default true,
  active_mode text not null default 'BASS' check (active_mode in ('BASS', 'AUTO', 'MANUAL')),
  accuracy integer not null default 65 check (accuracy between 0 and 100),
  win_rate integer not null default 78 check (win_rate between 0 and 100),
  updated_at timestamptz not null default now(),
  constraint one_settings_row check (id)
);

insert into public.aviator_signal_settings (id)
values (true)
on conflict (id) do nothing;

create table if not exists public.aviator_signal_audit_logs (
  id uuid primary key default gen_random_uuid(),
  action text not null,
  message text not null,
  actor_id uuid,
  created_at timestamptz not null default now()
);

alter table public.aviator_rounds enable row level security;
alter table public.aviator_signal_settings enable row level security;
alter table public.aviator_signal_audit_logs enable row level security;

create index if not exists aviator_rounds_fly_at_idx on public.aviator_rounds (fly_at desc);
create index if not exists aviator_rounds_status_idx on public.aviator_rounds (status);
create index if not exists aviator_signal_audit_logs_created_at_idx
  on public.aviator_signal_audit_logs (created_at desc);
