/* ============================================================
   Gameplay clips — GENERATED by scripts/sync_clips.py.

   Keyed by game id. Drop an .mp4/.webm into public/games/clips/
   named after the id and re-run the script; nothing else changes.
   See public/games/README.md.
   ============================================================ */

export const CLIPS: Record<string, string> = {
  'crazy-time': '/games/crazy-time.mp4',
};
