#!/usr/bin/env python3
"""
Index the gameplay clips in public/games/clips/ into lib/clips.ts.

Drop a file named after the game's id — the slug in /casino/<id> — and run
this; the fullscreen player will play it. No code change, no catalogue edit:

    public/games/clips/crazy-time.mp4   ->  /play/crazy-time plays it

Providers with no fun mode (every Evolution live table, most of the Asian
studios) have no demo URL to give, so a short self-hosted clip is the only
honest way to show what the game looks like. It is muted, looping and takes no
input, exactly like a demo frame.

    python3 scripts/sync_clips.py
"""
import os, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
CLIPS = ROOT / 'public' / 'games' / 'clips'
OUT = ROOT / 'lib' / 'clips.ts'
EXTS = ('.mp4', '.webm', '.ogg', '.mov')

found = {}
if CLIPS.is_dir():
    for f in sorted(CLIPS.iterdir()):
        if f.suffix.lower() in EXTS and not f.name.startswith('.'):
            found[f.stem] = f'/games/clips/{f.name}'

# the clip that predates this folder, kept where it already lives
legacy = ROOT / 'public' / 'games' / 'crazy-time.mp4'
if legacy.exists():
    found.setdefault('crazy-time', '/games/crazy-time.mp4')

rows = '\n'.join(f"  {k!r}: {v!r},".replace("'", "'") for k, v in sorted(found.items()))
OUT.write_text(f'''/* ============================================================
   Gameplay clips — GENERATED by scripts/sync_clips.py.

   Keyed by game id. Drop an .mp4/.webm into public/games/clips/
   named after the id and re-run the script; nothing else changes.
   See public/games/README.md.
   ============================================================ */

export const CLIPS: Record<string, string> = {{
{rows}
}};
''')
print(f'{len(found)} clip(s) indexed -> lib/clips.ts')
for k, v in sorted(found.items()):
    print(f'  {k:28} {v}')
